;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;
;; Beowulf  Sysout file generated at 2023-03-29T12:34:39.278
;; generated by simon
;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;;

((NULL
    LAMBDA (X) (COND ((EQUAL X (QUOTE NIL)) (QUOTE T)) ((QUOTE T) (QUOTE F))))
  (GCD
    LAMBDA
    (X Y)
    (COND
      ((GREATERP X Y) (GCD Y X))
      ((EQUAL (REMAINDER Y X) 0) X) ((QUOTE T) (GCD (REMAINDER Y X) X))))
  (NIL)
  (T . T)
  (F)
  (ADD1)
  (APPEND)
  (APPLY)
  (ATOM)
  (CAR)
  (CDR)
  (CONS)
  (DEFINE)
  (DIFFERENCE)
  (EQ)
  (EQUAL)
  (EVAL)
  (FIXP)
  (INTEROP)
  (NUMBERP)
  (OBLIST)
  (PLUS)
  (PRETTY)
  (QUOTIENT) (REMAINDER) (RPLACA) (RPLACD) (SET) (SYSIN) (SYSOUT) (TIMES))
